"""add auth_type and auth_token to monitors

Revision ID: 99a3faa533f4
Revises: 7997e168ffc3
Create Date: 2026-09-03 16:14:29.358409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a3faa533f4'
down_revision: Union[str, Sequence[str], None] = '7997e168ffc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('auth_type', sa.String(length=50), nullable=False, server_default='none'))
    op.add_column('monitors', sa.Column('auth_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'auth_token')
    op.drop_column('monitors', 'auth_type')
    # ### end Alembic commands ###
